### ISSUE TITLE
Consolidate bindings with ppx

### ISSUE THREAD

**Issue by jchavarri** [ahrefs/melange-react-intl-ppx#13]
Would be nice to put the bindings (the ReScript version currently is in https://github.com/cca-io/rescript-react-intl/) and the ppx in the same repo `melange-react-intl`. We can merge both repositories under this one using `git merge --allow-unrelated-histories`.

**Comment by ixzzd** [comment]
Does make sense, I will prepare a PR

**Comment by jchavarri** [comment]
This is being done in #15.
